# Generated by Django 4.2.8 on 2026-02-07 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('locked_by', models.ForeignKey(limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_locks_initiated', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_locks', to='core.classsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='screen_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'screen_locks',
                'ordering': ['-locked_at'],
            },
        ),
        migrations.CreateModel(
            name='CompilerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java')], max_length=20)),
                ('code', models.TextField()),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('execution_time', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compiler_submissions', to='core.classsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='compiler_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compiler_submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'session'], name='compiler_su_student_9b51e6_idx')],
            },
        ),
    ]
